### ISSUE TITLE
Similar to mp3 -> base64, how about png->base64

### ISSUE THREAD

**Issue by monetjoe** [MuGeminorum/eLuvLetter#2]
In the future, we shall convert pic files to base64 to make sure all items on the page are ready

**Comment by george-chou** [comment]
可将信封纹理转为base64编码

**Comment by monetjoe** [comment]
需求少，直接引用图片相对路径即可，主要是还包含大量分散的图片在css里，比较麻烦。解决音频加载就是抓大头了
